### ISSUE TITLE
Code Editor Repo not accessible

### ISSUE THREAD

**Issue by jdbcode** [adugnag/gee_s1_ard#1]
I tried running the https://github.com/adugnag/gee_s1_ard/blob/main/javascript/s1_ard.js script in the Code Editor and got a message:

> Cannot find required repo: users/adugnagirma/grs_ard:utilities

Loading the helper is fine:

```
var helper = require('users/adugnagirma/gee_s1_ard:utilities');
print(helper);
```

The problem occurs when loading the wrapper:

```
var wrapper = require('users/adugnagirma/gee_s1_ard:wrapper');
print(wrapper);
```

The wrapper must be importing the `grs_ard:utilities` module, which is either not shared or is maybe a typo?

**Comment by adugnag** [comment]
The problem originates in the border_noise_correction script line 7 while importing the utilities script. It was pointing at the wrong repo (grs_ard). The issue has been resolved now.

**Comment by jdbcode** [comment]
Still getting the same error

![image](https://user-images.githubusercontent.com/9044197/118734381-1740f100-b7f3-11eb-8d24-33760ed3987a.png)

https://code.earthengine.google.com/59af6ce7c5d61c759176cc61a4dca1a4

**Comment by adugnag** [comment]
It was the same issue as before. Now it truly resolved.
